### ISSUE TITLE
Flycheck error display error: (void-function flycheck-relevant-error-other-file-p)

### ISSUE THREAD

**Issue by bjc** [flycheck/flycheck-inline#13]
Issue #7 seems relevant, but I installed this package from git. Relevant commit is cf9eceabff8370f3b834b943a5777b9f914583f9 (master as of today).

I've gone through the code, and, indeed, there's no reference to that function except as called from `flycheck-inline--error-position`.

**Comment by cpitclaudel** [comment]
See https://github.com/flycheck/flycheck/blob/76e24628239eade428d40b88745b209121a845c2/flycheck.el#L3378 ; are you using an outdated flycheck?

**Comment by bjc** [comment]
Ah, my mistake. I was checking the flycheck-inline code, not flycheck itself.
