### ISSUE TITLE
Wrap long text

### ISSUE THREAD

**Issue by sandinmyjoints** [flycheck/flycheck-inline#14]
When the text of a message is wider than window-body, it is cut off by the window's edge. It'd be great if the message could wrap instead!

**Comment by cpitclaudel** [comment]
I agree.  Would you like to prepare a patch? I think  the simplest solution is to add a `wrap-prefix` on the error message in the error list, of the appropriate width.

**Comment by cpitclaudel** [comment]
Wait, actually: are you reporting this for flycheck in general, or specifically for flycheck-inline?

**Comment by fmdkdd** [comment]
`flycheck-inline` already wraps the text of an error, AFAIK.  Do you have a screenshot where it doesn't?

**Comment by sandinmyjoints** [comment]
Here's a screenshot:
![Screen Shot 2019-11-20 at 10 31 47 AM](https://user-images.githubusercontent.com/606772/69252497-13da9400-0b81-11ea-8635-af6760243b42.png)

I tried closing the left window and saw that after I did that, the text is wrapped:
![Screen Shot 2019-11-20 at 10 31 51 AM](https://user-images.githubusercontent.com/606772/69252528-248b0a00-0b81-11ea-97f2-9175234983bc.png)

I usually have two windows side by side, so wrapping in that case would be ideal!

**Comment by fmdkdd** [comment]
Hmm looks like `truncate-partial-width-windows` kicks in in the first screenshot.  Try to set that variable to a lower value, or even `nil` to disable its effect (and test that it is indeed the culprit!).

**Comment by sandinmyjoints** [comment]
Ah, thanks, that was the problem. It was being set to `t` in a long-forgotten prog-mode-hook.
