### ISSUE TITLE
Flycheck next/previous error functions do not trigger flycheck-inline

### ISSUE THREAD

**Issue by cheeze2000** [flycheck/flycheck-inline#18]
### Actual behaviour

Suppose my cursor was somewhere in line 3, after doing `C-c ! n` which is `(flycheck-next-error)`, the cursor will jump to the error (the pink underlined text) but there will be no error displayed.

![actual](https://cdn.discordapp.com/attachments/437471715975757834/738690589750591549/unknown.png)
---
### Expected behaviour

Since the underlined text is 2 characters, a workaround that I could use is `C-c ! n` and then `C-f` which will show me the error where the cursor is right at `'s'`. However, I am not sure if this is intended or not because if commands like `C-f` and `C-b` work, there is no reason for `C-c ! n` to not work.

![expected](https://cdn.discordapp.com/attachments/437471715975757834/738692826476314704/unknown.png)
---
Emacs 26.3 with `flycheck` and `flycheck-inline` as well as `ghc` installed
Ubuntu 20.04 LTS

**Comment by loafofpiecrust** [comment]
If you wanted to try out my branch, I think #17 fixes this issue as well.

**Comment by fmdkdd** [comment]
@cheeze2000 is your issue fixed with @loafofpiecrust's patch merged into master?
