### ISSUE TITLE
Align every line of the error message to the same column

### ISSUE THREAD

**Issue by mssdvd** [flycheck/flycheck-inline#3]
Currently only the first line is aligned to the error's column (see the screenshot).
Is it possible to align all the rows to the same column of the first row?
![image](https://user-images.githubusercontent.com/18464329/44271191-c662cf00-a239-11e8-8146-41dab6438cfc.png)

**Comment by fmdkdd** [comment]
Hmm, I cannot reproduce.  Here is what I get with rust 1.28:

![flycheck-inline-3](https://user-images.githubusercontent.com/340129/44332663-d6162980-a46c-11e8-8b72-59ffea8a00b3.png)

**Comment by fmdkdd** [comment]
And here is a multi-line warning:

![flycheck-inline-3-warn](https://user-images.githubusercontent.com/340129/44332729-14abe400-a46d-11e8-8aa1-63550f8ddaeb.png)

**Comment by mssdvd** [comment]
I apologise for not giving a more comprehensive description.
I was using `lsp-mode` + `lsp-ui` + [this patch](https://github.com/emacs-lsp/lsp-ui/pull/167) + `(setq lsp-ui-sideline-show-flycheck nil)`.

**Comment by fmdkdd** [comment]
Alright, thanks for clarifying.  My guess is that `lsp-mode` is producing error messages that contain newlines, and `flycheck-inline` only pads the first line of an error message, not all the lines.

Can you try the patch at #4 and see if that works for you?

**Comment by fmdkdd** [comment]
@mssdvd Thanks for confirming, I merged the change.
