### ISSUE TITLE
The `quick-peek` configuration shown in Readme doesn't work

### ISSUE THREAD

**Issue by happycoder97** [flycheck/flycheck-inline#5]
```elisp
(setq flycheck-inline-display-function
      (lambda (msg pos)
        (let* ((ov (quick-peek-overlay-ensure-at pos))
               (contents (quick-peek-overlay-contents ov)))
          (setf (quick-peek-overlay-contents ov)
                (concat contents (when contents "\n") msg))
          (quick-peek-update ov)))
      flycheck-inline-clear-function #'quick-peek-hide)
```
When the cursor reaches an erroneous word, the following error is displayed:
`Flycheck error display error: (void-function (setf quick-peek-overlay-contents))`

I am not sure what exactly is causing the error, but `quick-peek` seems to be broken if I enable flycheck-inline (https://github.com/cpitclaudel/quick-peek/issues/11)

**Comment by fmdkdd** [comment]
Be sure to `(require 'quick-peek)` before evaluating the above snippet, otherwise you might run into this error.

Can you reproduce using `emacs -Q` or from a minimal configuration?

**Comment by happycoder97** [comment]
`(require 'quick-peek)` fixed the issue. Thanks : )
